package service

var PHONETIC_ALPHABET = map[string]string {
	"u": "/1/",
	"ar": "/2/", "Cath": "/2/",
	"a": "/3/", "easE": "/3/",
	"Sa": "/4/",
	"ur": "/5/", "Cear": "/5/",
	"ie": "/6/", "yC": "/6/",
	"e": "/7/", "ee": "/7/", "ea": "/7/", "Cey": "/7/", "i": "/7/",
	"o": "/8/",
	"Cour": "/9/", "all": "/9/",
	"ut": "/10/", "pu": "/10/",
	"ue": "/11/", "oo": "/11/",
	"eye": "/12/",
	"ow": "/13/", "ou": "/13/",
	"ay": "/14/", "eigh": "/14/",
	"onV": "/15/", "omV": "/15/", "oE": "/15/",
	"oy": "/16/", "oi": "/16/",
	"Chere": "/17/", "air": "/17/",
	"ear": "/18/",
	"ere": "/19/",
	"ure": "/20/", "ourE": "/20/",

	"b": "/21/",
	"d": "/22/",
	"f": "/23/",
	"g": "/24/",
	"h": "/25/",
	"y": "/26/",
	"c": "/27/", "ck": "/27/", "k": "/27",
	"l": "/28/",
	"m": "/29/",
	"n": "/30/",
	"ing": "/31/",
	"p": "/32/",
	"r": "/33/",
	"s": "/34/", "ss": "/34/",
	"sh": "/35/",
	"t": "/36/", "tt": "/36/",
	"ch": "/37/",
	"thin": "/38/", "oth": "/38/",
	"th": "/39/",
	"v": "/40/",
	"w": "/41/",
	"z": "/42/",
	"eas": "/43/", "is": "/43/", "ys": "/43/",
	"j": "/44/",
	"ge": "/44/",
}

var CONSONANTS = "bcdfghjklmnpqrstvwxyz"
var VOWELS = "aeiou"
var phoneticLargest = []string{"Chere", "Cath", "easE", "Cear", "Cour", "eigh", "ourE", "thin", "Cey", "all", "eye", "onV", "omV", "air", "ear", "ere", "ure", "ing", "oth", "eas", "ar", "Sa", "ur", "ie", "yC", "ee", "ea", "ut", "pu", "ue", "oo", "ow", "ou", "ay", "oE", "oy", "oi", "ck", "ss", "sh", "tt", "ch", "th", "is", "ys", "ge", "u", "a", "e", "i", "o", "b", "d", "f", "g", "h", "y", "c", "k", "l", "m", "n", "p", "r", "s", "t", "v", "w", "z", "j"}
